version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "houkiserver-web-api"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
